steps:
- task: PowerShell@2
  displayName: Install Required Modules
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
          $sdk = Get-InstalledModule Microsoft.Graph
          echo "Current version "+$sdk.Version
          echo "Updating to the latest sdk version"
          Update-Module Microsoft.Graph -Scope CurrentUser
          Import-Module Microsoft.Graph -Global -Force  

- template: ../common-templates/checkout.yml